import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { GoogleGenAI } from '@google/genai'

const supabaseAdmin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
)

// POST /api/compliance-autopilot/generate-doc
// Generate a legal document for a resolution step and save to Document Vault
export async function POST(request: NextRequest) {
    const apiKey = process.env.GEMINI_API_KEY
    if (!apiKey) return NextResponse.json({ error: 'AI unavailable' }, { status: 500 })

    const authHeader = request.headers.get('authorization')
    if (!authHeader) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const supabase = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        { global: { headers: { Authorization: authHeader } } }
    )
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    let body: any
    try { body = await request.json() } catch {
        return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
    }

    const { resolution_id, step_index, property, violation } = body
    if (!resolution_id || step_index === undefined || !property || !violation) {
        return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
    }

    const { data: res } = await supabaseAdmin
        .from('violation_resolutions').select('*').eq('id', resolution_id).single()
    const step = res?.ai_action_plan?.[step_index]
    if (!step) return NextResponse.json({ error: 'Step not found' }, { status: 404 })

    // Determine document type from step category
    const docTypeMap: Record<string, string> = {
        Paperwork: 'Affidavit of Compliance',
        Plumbing: 'Work Order — Plumbing',
        Electrical: 'Work Order — Electrical',
        HVAC: 'Work Order — HVAC',
        'Lead Abatement': 'Lead Clearance Certification',
        General: 'Inspection Request Letter',
    }
    const docType = docTypeMap[step.category] || 'Compliance Document'

    const ai = new GoogleGenAI({ apiKey })
    const prompt = `
You are an expert NYC real estate compliance attorney.
Generate a formal "${docType}" document for the following situation.

Property: ${property.address}, New York, NY
BIN: ${property.bin || 'N/A'} | BBL: ${property.bbl || 'N/A'}
Violation: ${violation.description || violation.novdescription}
Violation Class: ${violation.class || 'N/A'}
Resolution Step: ${step.title} — ${step.description}

Requirements:
1. Write in formal legal English, ready for signature and notarization.
2. State that the violation has been corrected per NYC administrative codes.
3. Format as clean semantic HTML (h1, h2, p, strong, br). NO markdown code blocks.
4. Include signature block: Owner/Agent, Date, Print Name, Notary Public section.
5. Include the current date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}.
`

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: { temperature: 0.1 },
    })

    const html = (response.text || '').replace(/^```(html)?\n?/i, '').replace(/\n?```$/i, '').trim()

    // Store in Document Vault DB entry (we store as HTML, not binary)
    const docEntry = {
        property_id: property.id,
        uploaded_by: user.id,
        file_name: `autopilot_${docType.replace(/\s+/g, '_')}_${Date.now()}.html`,
        file_url: '', // Will be stored inline in ai_summary for HTML docs
        file_type: 'text/html',
        file_size_bytes: html.length,
        category: 'certificate' as const,
        ai_summary: `AI-generated ${docType} for violation: ${violation.description?.substring(0, 80)}`,
        ai_processed: true,
        tags: ['autopilot', 'generated'],
        notes: `Generated by AI Autopilot for Resolution #${resolution_id}, Step ${step_index + 1}: ${step.title}`,
    }

    const { data: savedDoc } = await supabaseAdmin
        .from('documents').insert(docEntry).select().single()

    // Also attach to resolution's generated_documents
    if (res?.generated_documents) {
        const existingDocs = [...(res.generated_documents || [])]
        existingDocs.push({
            type: docType,
            document_id: savedDoc?.id,
            html_content: html,
            created_at: new Date().toISOString(),
            step_index,
        })
        await supabaseAdmin
            .from('violation_resolutions')
            .update({ generated_documents: existingDocs })
            .eq('id', resolution_id)
    }

    return NextResponse.json({
        html,
        document_id: savedDoc?.id,
        doc_type: docType,
    })
}
