import React from 'react';

interface AffidavitTemplateProps {
    property: any;
    violation: any;
    htmlContent: string;
}

export default function AffidavitTemplate({ property, violation, htmlContent }: AffidavitTemplateProps) {
    return (
        <div id="affidavit-report-container" className="bg-white text-black p-12 max-w-4xl mx-auto shadow-2xl relative" style={{ width: '800px', minHeight: '1100px' }}>
            {/* Header */}
            <div className="border-b-4 border-slate-800 pb-6 mb-8 flex justify-between items-end">
                <div>
                    <h1 className="text-4xl font-serif font-bold text-slate-900 leading-tight">Evereez</h1>
                    <p className="text-sm font-sans text-slate-600 mt-1 uppercase tracking-widest">Official Legal Correspondence</p>
                </div>
                <div className="text-right">
                    <p className="font-bold text-slate-800">AFFIDAVIT OF COMPLIANCE</p>
                    <p className="text-sm text-slate-500">Date: {new Date().toLocaleDateString()}</p>
                </div>
            </div>

            {/* Property Details Summary */}
            <div className="bg-slate-50 border border-slate-200 p-6 rounded mb-8">
                <h3 className="text-xs font-bold uppercase text-slate-500 mb-3 tracking-wider">Property Information</h3>
                <div className="grid grid-cols-2 gap-4 text-sm">
                    <div><span className="text-slate-500">Address:</span> <strong className="text-slate-800">{property?.address}, {property?.borough}, NY</strong></div>
                    <div><span className="text-slate-500">Violation #:</span> <strong className="text-red-600">{violation?.id}</strong></div>
                    <div><span className="text-slate-500">BIN:</span> <strong className="text-slate-800">{property?.bin || 'N/A'}</strong></div>
                    <div><span className="text-slate-500">Class:</span> <strong className="text-amber-600 font-bold">{violation?.class}</strong></div>
                </div>
            </div>

            {/* AI Generated Legal Text */}
            <div className="prose prose-slate max-w-none text-slate-800 font-serif leading-relaxed" dangerouslySetInnerHTML={{ __html: htmlContent }} />

            {/* Footer */}
            <div className="absolute bottom-12 w-[calc(100%-6rem)] flex justify-between items-end border-t border-slate-300 pt-6 text-xs text-slate-500">
                <p>Generated by NYC Compliance Shield AI<br />Verify at nyc.gov/dob</p>
                <p className="text-right">Page 1 of 1<br />Document ID: {Math.random().toString(36).substr(2, 9).toUpperCase()}</p>
            </div>
        </div>
    );
}
