
import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env' })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing Supabase credentials')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseKey)

async function createContractorsTable() {
  console.log('Creating contractors table...')

  // 1. Create the table SQL
  const createTableQuery = `
    create table if not exists public.contractors (
      id bigint generated by default as identity primary key,
      created_at timestamp with time zone default timezone('utc'::text, now()) not null,
      name text not null,
      category text not null, -- Plumbing, Electrical, HVAC, General, etc.
      phone text,
      email text,
      status text default 'Active', -- Active, Inactive, Pending
      rating numeric default 5.0,
      reviews integer default 0,
      verified boolean default false,
      company text,
      location text,
      image text
    );
  `

  // 2. Enable RLS and Policies SQL
  const enableRLS = `alter table public.contractors enable row level security;`

  // Allow everyone to read (Managers need to see the list)
  const policyRead = `
    create policy "Enable read access for all users"
    on public.contractors for select
    using (true);
  `

  // Allow authenticated users (Admins/Managers) to insert/update
  // For stricter control, we would check user_metadata role, but for now allow auth users
  const policyInsert = `
    create policy "Enable insert for authenticated users"
    on public.contractors for insert
    with check (auth.role() = 'authenticated');
  `

  const policyUpdate = `
    create policy "Enable update for authenticated users"
    on public.contractors for update
    using (auth.role() = 'authenticated');
  `

  // Execute SQL via RPC is restricted, so we will use the text query if possible or guide user.
  // Since we don't have direct SQL execution capability via SDK for DDL without special setup, 
  // we will try to insert a dummy record to check if table exists, if not we log strict instructions.
  // Note: Standard Supabase SDK doesn't support 'create table' directly.
  // WE WILL PRINT THE SQL FOR THE USER TO RUN IN DASHBOARD SQL EDITOR if we can't do it.

  console.log("--- IMPORTANT: PLEASE RUN THIS SQL IN YOUR SUPABASE SQL EDITOR ---")
  console.log(createTableQuery)
  console.log(createPropertiesTableQuery)
  console.log(createRequestsTableQuery)

  console.log(enableRLS)
  console.log(policyRead)
  console.log(policyInsert)
  console.log(policyUpdate)

  console.log("\n--- FOR EXISTING TABLES, RUN THESE ALTER COMMANDS ---")
  console.log("alter table public.contractors add column if not exists company text;")
  console.log("alter table public.contractors add column if not exists location text;")
  console.log("alter table public.contractors add column if not exists image text;")
  console.log("------------------------------------------------------------------")
}

createContractorsTable()
