
import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env' })

const db_update_sql = `
-- 1. PROPERTIES 테이블 업데이트 (Access Code 추가)
alter table public.properties add column if not exists access_code text;
-- 기존 데이터에 랜덤 코드 부여 (임시)
update public.properties set access_code = floor(random() * 900000 + 100000)::text where access_code is null;

-- 2. REQUESTS 테이블 업데이트 (카테고리, 상세내용, 상태관리 강화)
create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  issue text,
  type text,
  status text default 'Pending',
  priority text default 'Medium',
  unit text,
  tenant_name text, -- snake_case
  date text, -- legacy support if needed, but created_at is better
  tenantName text -- legacy support if needed
);

-- Ensure columns exist (for migration or fresh table)
alter table public.requests add column if not exists category text default 'General'; 
alter table public.requests add column if not exists description text;
alter table public.requests add column if not exists property_id bigint;
alter table public.requests add column if not exists tenant_id uuid;
alter table public.requests add column if not exists attachments text[];
alter table public.requests add column if not exists tenant_name text; 
alter table public.requests add column if not exists issue text; 
alter table public.requests add column if not exists type text; 
alter table public.requests add column if not exists status text default 'Pending'; 
alter table public.requests add column if not exists priority text default 'Medium'; 
alter table public.requests add column if not exists unit text;
alter table public.requests add column if not exists contact_preference text;
alter table public.requests add column if not exists assigned_pro_id bigint;


-- 3. TENANTS 테이블 생성 (입주민 관리)
create table if not exists public.tenants (
  id uuid primary key, -- Matches auth.users.id
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  property_id bigint references public.properties(id),
  unit_number text not null,
  status text default 'Pending', -- Pending, Approved, Rejected
  lease_start date,
  lease_end date
);
alter table public.tenants enable row level security;

-- Policies (Dropped first to avoid errors)
drop policy if exists "Enable read access for all" on public.tenants;
create policy "Enable read access for all" on public.tenants for select using (true);

drop policy if exists "Enable insert for authenticated" on public.tenants;
create policy "Enable insert for authenticated" on public.tenants for insert with check (auth.role() = 'authenticated');

drop policy if exists "Enable update for users" on public.tenants;
create policy "Enable update for users" on public.tenants for update using (auth.uid() = id);

-- 4. PROFILES TABLE & TRIGGER (User Management)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text default 'tenant',
  full_name text,
  status text default 'Pending', -- Pending, Active, Suspended
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.profiles enable row level security;
-- Policies for Profiles
drop policy if exists "Public profiles are viewable by everyone" on public.profiles;
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  -- 1. Insert into Profiles
  insert into public.profiles (id, email, role, full_name, status)
  values (new.id, new.email, new.raw_user_meta_data->>'role', new.raw_user_meta_data->>'full_name', 'Pending');
  
  -- 2. If Tenant with Property ID (from access code), insert into Tenants table
  if (new.raw_user_meta_data->>'role' = 'tenant' and new.raw_user_meta_data->>'property_id' is not null) then
      begin
        insert into public.tenants (id, property_id, unit_number, status, created_at)
        values (
            new.id, 
            (new.raw_user_meta_data->>'property_id')::bigint, 
            'N/A', -- Will need to be updated by tenant later
            'Pending',
            now()
        );
      exception when others then
        -- Ignore error if tenant insert fails, user still created
        null;
      end;
  end if;

  return new;
end;
$$ language plpgsql security definer;

-- Trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. SYNC EXISTING USERS (기존 사용자 프로필 생성)
insert into public.profiles (id, email, role, full_name, status)
select id, email, raw_user_meta_data->>'role', raw_user_meta_data->>'full_name', 'Active'
from auth.users
on conflict (id) do nothing;

-- 7. CONFIRM EMAILS (이메일 인증 강제 처리)
update auth.users set email_confirmed_at = now() where email_confirmed_at is null;

-- 8. RPC: Admin이 승인 시 이메일도 인증 처리하는 함수
create or replace function public.approve_user(target_id uuid)
returns void as $$
begin
  -- 1. Profile 상태 Active로 변경
  update public.profiles set status = 'Active' where id = target_id;
  -- 2. Auth User 이메일 인증 처리
  update auth.users set email_confirmed_at = now() where id = target_id;
end;
$$ language plpgsql security definer;

-- 9. RPC: Admin이 사용자 삭제 (Hard Delete)
create or replace function public.delete_user(target_id uuid)
returns void as $$
begin
  -- 1. Clear references in profiles that point to the properties we're about to delete
  update public.profiles 
  set property_id = null 
  where property_id in (select id from public.properties where manager_id = target_id);

  -- 2. Related data in properties-dependent tables
  delete from public.contractor_reviews 
  where reviewer_id = target_id 
     or property_id in (select id from public.properties where manager_id = target_id);

  delete from public.requests 
  where tenant_id = target_id 
     or property_id in (select id from public.properties where manager_id = target_id);

  delete from public.tenants 
  where id = target_id 
     or property_id in (select id from public.properties where manager_id = target_id);

  -- 3. Properties (Cascades to documents, resolutions)
  delete from public.properties where manager_id = target_id;

  -- 4. Contractors (Safely check if column exists)
  if exists (
    select 1 from information_schema.columns 
    where table_schema = 'public' and table_name = 'contractors' and column_name = 'manager_id'
  ) then
    execute format('delete from public.contractors where manager_id = %L', target_id);
  end if;

  -- 5. Profiles
  delete from public.profiles where id = target_id;

  -- 6. Auth User
  delete from auth.users where id = target_id;
end;
$$ language plpgsql security definer;

-- 10. RPC: Property 삭제 (Hard Delete)
create or replace function public.delete_property(target_id bigint)
returns void as $$
begin
  -- 1. Clear references in profiles
  update public.profiles 
  set property_id = null 
  where property_id = target_id;

  -- 2. Related data
  delete from public.contractor_reviews where property_id = target_id;
  delete from public.requests where property_id = target_id;
  delete from public.tenants where property_id = target_id;
  delete from public.violation_resolutions where property_id = target_id;
  delete from public.documents where property_id = target_id;

  -- 3. Delete property
  delete from public.properties where id = target_id;
end;
$$ language plpgsql security definer;

-- 11. REQUESTS RLS POLICIES (Fix missing requests issue)
alter table public.requests enable row level security;

drop policy if exists "Enable read access for all" on public.requests;
create policy "Enable read access for all" on public.requests for select using (true);

drop policy if exists "Enable insert for authenticated" on public.requests;
create policy "Enable insert for authenticated" on public.requests for insert with check (auth.role() = 'authenticated');

drop policy if exists "Enable update for all" on public.requests;
create policy "Enable update for all" on public.requests for update using (true);

`;

console.log("--- RUN THIS SQL IN SUPABASE EDITOR ---")
console.log(db_update_sql)
console.log("---------------------------------------")
